main:
  push:
    - stages:
        - name: build-and-push-image
          script: |
            docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
            docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
      services:
        - docker

$:
  vscode:
    - if: $CNB_BRANCH == "main"
      runner:
        cpus: 16
      services:
        - docker
        - name: vscode
          options:
            onlyPreview: true
            launch: docker run -d --network host -e PORT=8686 -e CNB_API_ENDPOINT -e CNB_REPO_SLUG -e CNB_TOKEN ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
            keepAliveTimeout: 3600000
            daemon: true
    - if: $CNB_BRANCH == "dev"
      runner:
        cpus: 16
      services:
        - docker
        - vscode
